version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 713850109772.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Fetching secrets from Secrets Manager...
      - aws sts get-caller-identity
      - aws secretsmanager get-secret-value --secret-id my-env-file --region ap-northeast-2 --query SecretString --output text
      - echo Debugging with AWS CLI...
      - aws secretsmanager get-secret-value --secret-id my-env-file --region ap-northeast-2 --query SecretString --output text > .env --debug
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t monolithicarchitecture-spring-boot-app .
      - docker tag monolithicarchitecture-spring-boot-app:latest 713850109772.dkr.ecr.ap-northeast-2.amazonaws.com/monolithicarchitecture-spring-boot-app:latest
      - echo "Loading environment variables from .env..."
      - export $(cat .env | xargs)
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 713850109772.dkr.ecr.ap-northeast-2.amazonaws.com/monolithicarchitecture-spring-boot-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"monolithic","imageUri":"%s"}]' 713850109772.dkr.ap-northeast-2.amazonaws.com/monolithicarchitecture-spring-boot-app:latest > imagedefinitions.json
      - echo "Generated imagedefinitions.json:"
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
