global:
  scrape_interval: 15s # 메트릭 수집 주기

scrape_configs:
  - job_name: 'monolithic'
    metrics_path: '/actuator/prometheus' # Spring Boot에서 노출된 Prometheus 메트릭 엔드포인트
    static_configs:
      - targets: ['monolithicarchitecture-spring-boot-app-1:8080'] # Spring Boot 애플리케이션 주소
