aws:
  region: ap-northeast-2
  access-key: ${IAM_access_key}
  secret-access-key: ${IAM_secret_access_key}
  s3:
    bucket-name: ${S3_bucket_name}

spring:
  datasource:
    url: jdbc:mysql://${RDS_endpoint}:3306/feedback
    username: ${RDS_user_name}
    password: ${RDS_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus # prometheus 엔드포인트 노출
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: monolithic # 모든 메트릭에 추가될 태그